### ISSUE TITLE
Reuse existing role to setup docker-storage

### ISSUE THREAD

**Issue by lukas-bednar** [cynepco3hahue/kubevirt-ansible#2]
https://github.com/cynepco3hahue/kubevirt-ansible/blob/04d003a35955aead5387b79461f1c65ea80eda86/openshift/roles/docker-setup/tasks/main.yaml#L1

Hi,

there are already several maintained roles on ansible galaxy which does this job,
I think you can simple reuse ...

for example this looks good https://galaxy.ansible.com/mkubenka/docker-storage-setup/

or since you are working with openshift playbooks, I can see that they have such role in openshift-ansible-contrib repository as well: https://github.com/openshift/openshift-ansible-contrib/tree/master/roles/docker-storage-setup

**Comment by cynepco3hahue** [comment]
@lukas-bednar Yes I took it from `/openshift-ansible-contrib/tree/master/roles/docker-storage-setup`, I just did not want to clone an additional repo and this role is the small one so I just copied it.
Maybe do you know if it possible to take roles straight forward from GitHub repos?

**Comment by lukas-bednar** [comment]
what I do is using ansible-galaxy to obtain roles. put your deps into `requirements.yml`
```yaml
---
- src: https://github.com/openshift/openshift-ansible-contrib
  name: openshift-contrib
```

you need to obtain them via
```bash
$ ansible-galaxy install -p my-depending-roles -r requirements.yml
```

and then create playbook like
```yaml
---
- hosts: servers
  roles:
    - "openshift-contrib/roles/docker-storage-setup"
```

and run like
```bash
$ export ANSIBLE_ROLES_PATH=my-depending-roles
$ ansible-playbook -i inventory my-playbook.yml
```
